import { Inter } from 'next/font/google';
import { AppContainer } from './components/styled/AppContainer.styled';
import Head from 'next/head';
import Header from './components/Header';
import Hero from './components/Hero';
import Walkthrough from './components/Walkthrough';
import Products from './components/Products';
import { GetServerSideProps } from 'next';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    // <AppContainer>
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>
      <Header />
      // <Hero />
      <Walkthrough /> *
    </>
    //   {/* <Products data={data} />
    //   {/* <Footer /> */}
    // </AppContainer>
  );
}

const headers = {
  'Content-Type': 'application/json',
  Accept: 'application/json',
  Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM5ODQ2MDdiNWE0NTAwMjFiNWY1MDEiLCJpYXQiOjE2ODE0OTEwNDB9.M9Mdl9O9jqyO1Nxy0Jaw0rXoa_k07fo_hE7-Rv3eKvY`,
};
